/*
 *  Copyright (C) 2016 FAAC - Faculdade de Arquitetura, Artes e Comunicação
 *  UNESP - Universidade Estadual Paulista “Júlio de Mesquita Filho”
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package br.unesp.sgcd;

import br.unesp.sgcd.beans.Usuario;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

/**
 *
 * @author demitrius
 */
public class AdicionarUsuario extends javax.swing.JDialog {

    private final UserListModel listModel = new UserListModel();
    private final Service service = Service.getInstance();

    /**
     * Creates new form AdicionarUsuario
     */
    public AdicionarUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jList1.setCellRenderer(new UserListCellRenderer());
        carregaLista();
    }

    private boolean ok = false;

    public boolean isOk() {
        return ok;
    }

    private void carregaLista() {
        List<UserListItem> lista = new ArrayList<UserListItem>();
        List<Usuario> l = Collections.EMPTY_LIST;
        if (radioUsuarios.isSelected()) {
            l = service.findUsuarios("U");
        } else if (radioGrupos.isSelected()) {
            l = service.findUsuarios("G");
        } else {
            l = service.findUsuarios(null);
        }
        for (Usuario u : l) {
            UserListItem userListItem = new UserListItem(u);
            lista.add(userListItem);
        }
        Collections.sort(lista, new Comparator<UserListItem>() {
            @Override
            public int compare(UserListItem o1, UserListItem o2) {
                if (o1.getUsuario().getNome().compareTo(o2.getUsuario().getNome()) != 0) {
                    return o1.getUsuario().getNome().compareTo(o2.getUsuario().getNome());
                }
                return o1.getUsuario().getLogin().compareTo(o2.getUsuario().getLogin());
            }
        });
        listModel.setList(lista);
    }

    public List<UserListItem> getListaSelecionados() {
        List<UserListItem> list = new ArrayList<UserListItem>();
        for (int i : jList1.getSelectedIndices()) {
            UserListItem u = listModel.getList().get(i);
            u.setNovo(true);
            list.add(u);
        }
        return list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        radioUsuarios = new javax.swing.JRadioButton();
        radioGrupos = new javax.swing.JRadioButton();
        radioAmbos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        btnCancelar = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Usuário");

        buttonGroup1.add(radioUsuarios);
        radioUsuarios.setText("Usuários");
        radioUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioUsuariosActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioGrupos);
        radioGrupos.setText("Grupos");
        radioGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGruposActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioAmbos);
        radioAmbos.setSelected(true);
        radioAmbos.setText("Ambos");
        radioAmbos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAmbosActionPerformed(evt);
            }
        });

        jList1.setModel(listModel);
        jScrollPane1.setViewportView(jList1);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioUsuarios)
                        .addGap(18, 18, 18)
                        .addComponent(radioGrupos)
                        .addGap(18, 18, 18)
                        .addComponent(radioAmbos)
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioUsuarios)
                    .addComponent(radioGrupos)
                    .addComponent(radioAmbos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnOk))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        ok = true;
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void radioUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioUsuariosActionPerformed
        carregaLista();
    }//GEN-LAST:event_radioUsuariosActionPerformed

    private void radioGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGruposActionPerformed
        carregaLista();
    }//GEN-LAST:event_radioGruposActionPerformed

    private void radioAmbosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAmbosActionPerformed
        carregaLista();
    }//GEN-LAST:event_radioAmbosActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdicionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdicionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdicionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdicionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                AdicionarUsuario dialog = new AdicionarUsuario(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioAmbos;
    private javax.swing.JRadioButton radioGrupos;
    private javax.swing.JRadioButton radioUsuarios;
    // End of variables declaration//GEN-END:variables
}
